version: '1'
services:

  api:
    build: ./server/
    container_name: api
    ports:
      - "3700:3700"
    volumes:
      - "./server/:/app"
      - "/app/node_modules"
    environment:
      - MONGO_URI=mongodb://anasch07:anasch07@db-mongo:27017
    command: npm start

  web:
    build: ./client/
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    command: npm start

  db-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: anasch07
      MONGO_INITDB_ROOT_PASSWORD: anasch07
    volumes:
      - db-data-mongo:/data/db

volumes:
  db-data-mongo: {}
    