FROM --platform=linux/arm64,linux/amd64 node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . ./

ENV PORT=3700

EXPOSE ${PORT}
WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . ./

ENV PORT=3700

EXPOSE ${PORT}
