name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push multi-arch API Docker image with caching
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: true
        tags: anasch07/tp2-devops-docker-compose-github-actions-mern-crud-api:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
    

    # - name: Set up Docker buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Build Image multi arch
    #   run: docker buildx build --platform linux/arm64,linux/amd64 -t anasch07/tp2-devops-docker-compose-github-actions-mern-crud-api:latest --push ./server
       

    # - name: Build and push API Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: ./server
    #     push: true
    #     tags: anasch07/tp2-devops-docker-compose-github-actions-mern-crud-api:latest
    #     platform: linux/amd64

    # - name: Build and push Web Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: ./client
    #     push: true
    #     tags: anasch07/tp2-devops-docker-compose-github-actions-mern-crud-web:latest
    #     platform: linux/amd64
